### ISSUE TITLE
Error detected while opening a GUI instance

### ISSUE THREAD

**Issue by sumitst05** [Rishabh672003/Neovim#16]
Opening a terminal instance of neovim is working fine but while opening  a GUI instance I get the following error:

![swappy-20230223_213221](https://user-images.githubusercontent.com/106669732/220965330-caf04647-8f71-4369-b2d3-e3ee2e451db1.png)

Although removing line 49 from options.lua works temporarily

**Comment by Rishabh672003** [comment]
you are using nvim-0.8 right? yeah that will not work there as thats a new feature introduced in nvim main branch i think

**Comment by Rishabh672003** [comment]
i didnt read the gui part i am blind, so which gui are you running? it can be because of my previous comment but i have no idea

**Comment by sumitst05** [comment]
> you are using nvim-0.8 right? yeah that will not work there as thats a new feature introduced in nvim main branch i think

I am using nightly as well which got installed when I ran your automation script

**Comment by Rishabh672003** [comment]
oh never though someone else would use that, but i would say what you should use for nvim-nightly is this https://github.com/MordechaiHadad/bob

**Comment by Rishabh672003** [comment]
also which gui? you didnt answer that

**Comment by sumitst05** [comment]
> also which gui? you didnt answer that

neovim-gtk

**Comment by Rishabh672003** [comment]
yeah now i get it, actually with neovim-gtk you arent using the nvim-nightly because that only runs with neovim-0.8, when you have installed it you from Aur i suppose you might have noticed it installs nvim-0.8

**Comment by sumitst05** [comment]
I think this issue occured because I already had neovim installed ... Just removed all packages and ran the automation script and everything's fine

**Comment by sumitst05** [comment]
> yeah now i get it, actually with neovim-gtk you arent using the nvim-nightly because that only runs with neovim-0.8, when you have installed it you from Aur i suppose you might have noticed it installs nvim-0.8 

Yeah! You beat me to it 😂

**Comment by Rishabh672003** [comment]
so closing the issue now,
